# Generated by Django 5.2.7 on 2025-10-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_healthpackage_insurance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthpackage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/healthpackage/'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/insurance/'),
        ),
    ]
