# Generated by Django 5.2.7 on 2025-10-09 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contactrequest',
            table='contact_request',
        ),
    ]
